package com.example.util

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Rect
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.os.Build
import android.text.Layout
import android.text.StaticLayout
import android.text.TextPaint
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.data.AiAnalysisRecord
import java.io.File
import java.io.FileOutputStream

object PdfReportGenerator {

    /**
     * Generates a single-page PDF inspection summary report for a specific drosophila specimen analysis
     * and immediately launches the system share sheet.
     */
    fun generateAndShareReport(context: Context, record: AiAnalysisRecord) {
        try {
            val pdfFile = createPdfReport(context, record)
            if (pdfFile == null || !pdfFile.exists()) {
                Toast.makeText(context, "Failed to create PDF report", Toast.LENGTH_SHORT).show()
                return
            }

            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.provider",
                pdfFile
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_SUBJECT, "Drosophila Specimen Inspection Report - ${record.formattedDate}")
                putExtra(
                    Intent.EXTRA_TEXT,
                    "Attached is the Drosophila inspection analysis report generated by FlyVision.\nDate: ${record.formattedDate}\n\nSummary:\n${record.apiResponse.take(240)}..."
                )
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            val chooser = Intent.createChooser(shareIntent, "Share Inspection Report (PDF)").apply {
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            context.startActivity(chooser)
        } catch (e: Exception) {
            e.printStackTrace()
            Toast.makeText(context, "Error sharing report: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    private fun createPdfReport(context: Context, record: AiAnalysisRecord): File? {
        val document = PdfDocument()
        val pageWidth = 595 // Standard A4 points: 595 x 842 pt
        val pageHeight = 842
        val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
        val page = document.startPage(pageInfo)
        val canvas = page.canvas

        val paint = Paint(Paint.ANTI_ALIAS_FLAG)
        val margin = 36f
        val contentWidth = pageWidth - (margin * 2)

        // 1. Header Banner
        paint.color = Color.rgb(15, 23, 42) // Slate 900
        canvas.drawRect(0f, 0f, pageWidth.toFloat(), 70f, paint)

        paint.color = Color.rgb(16, 185, 129) // Emerald 500 accent bar
        canvas.drawRect(0f, 66f, pageWidth.toFloat(), 70f, paint)

        paint.color = Color.WHITE
        paint.textSize = 15f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("FLYVISION • DROSOPHILA INSPECTION REPORT", margin, 38f, paint)

        paint.color = Color.rgb(203, 213, 225)
        paint.textSize = 9f
        paint.typeface = Typeface.DEFAULT
        canvas.drawText("Neurological Visual Surface & Defect Diagnostic Summary", margin, 54f, paint)

        // 2. Metadata Card
        var currentY = 90f
        paint.color = Color.rgb(241, 245, 249) // Light card background
        val metaCardRect = RectF(margin, currentY, pageWidth - margin, currentY + 68f)
        canvas.drawRoundRect(metaCardRect, 8f, 8f, paint)

        paint.color = Color.rgb(51, 65, 85)
        paint.textSize = 10f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        val reportId = if (record.id > 0) "#DSP-${record.id}" else "#DSP-${record.timestamp % 100000}"
        canvas.drawText("Report ID: $reportId", margin + 14f, currentY + 22f, paint)

        paint.typeface = Typeface.DEFAULT
        paint.color = Color.rgb(100, 116, 139)
        canvas.drawText("Timestamp: ${record.formattedDate}", margin + 14f, currentY + 38f, paint)
        canvas.drawText("Specimen: Drosophila melanogaster", margin + 14f, currentY + 54f, paint)

        // Status badge inside meta card
        val badgeX = pageWidth - margin - 120f
        val badgeY = currentY + 16f
        val isAnomalous = record.apiResponse.contains("anomal", ignoreCase = true) ||
                record.apiResponse.contains("defect", ignoreCase = true) ||
                record.apiResponse.contains("scratch", ignoreCase = true)

        paint.color = if (isAnomalous) Color.rgb(239, 68, 68) else Color.rgb(16, 185, 129)
        canvas.drawRoundRect(RectF(badgeX, badgeY, badgeX + 106f, badgeY + 24f), 12f, 12f, paint)

        paint.color = Color.WHITE
        paint.textSize = 8.5f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        val badgeText = if (isAnomalous) "DEFECT FLAGGED" else "INSPECTION PASS"
        val textWidth = paint.measureText(badgeText)
        canvas.drawText(badgeText, badgeX + (106f - textWidth) / 2f, badgeY + 16f, paint)

        currentY += 82f

        // 3. Specimen Image (if available)
        val bitmap = loadSpecimenBitmap(context, record.imageUri)
        if (bitmap != null) {
            val imgBoxWidth = 180f
            val imgBoxHeight = 130f
            val imgRect = RectF(margin, currentY, margin + imgBoxWidth, currentY + imgBoxHeight)

            // Draw image border background
            paint.color = Color.rgb(226, 232, 240)
            canvas.drawRoundRect(imgRect, 6f, 6f, paint)

            val scaledBitmap = scaleBitmapToFit(bitmap, imgBoxWidth.toInt(), imgBoxHeight.toInt())
            val drawX = margin + (imgBoxWidth - scaledBitmap.width) / 2f
            val drawY = currentY + (imgBoxHeight - scaledBitmap.height) / 2f
            canvas.drawBitmap(scaledBitmap, drawX, drawY, null)

            // Draw side details
            val sideX = margin + imgBoxWidth + 16f
            paint.color = Color.rgb(30, 41, 59)
            paint.textSize = 11f
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            canvas.drawText("Specimen Visual Capture", sideX, currentY + 22f, paint)

            paint.typeface = Typeface.DEFAULT
            paint.textSize = 9.5f
            paint.color = Color.rgb(71, 85, 105)
            canvas.drawText("• Optical Method: Close-up Macro Lens", sideX, currentY + 44f, paint)
            canvas.drawText("• Illumination: Artificial LED Flashlight", sideX, currentY + 62f, paint)
            canvas.drawText("• Neural Model: Gemini Multimodal Vision", sideX, currentY + 80f, paint)
            canvas.drawText("• Verified: Drosophila Physical Integrity", sideX, currentY + 98f, paint)

            currentY += imgBoxHeight + 20f
        }

        // 4. Detailed Analysis Findings Section
        paint.color = Color.rgb(30, 41, 59)
        paint.textSize = 12f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("NEUROLOGICAL INSPECTION FINDINGS", margin, currentY, paint)

        currentY += 6f
        paint.color = Color.rgb(203, 213, 225)
        paint.strokeWidth = 1f
        canvas.drawLine(margin, currentY, pageWidth - margin, currentY, paint)

        currentY += 14f

        val textPaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.rgb(30, 41, 59)
            textSize = 9.5f
            typeface = Typeface.DEFAULT
        }

        val availableTextHeight = pageHeight - margin - 35f - currentY
        val textLayout = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            StaticLayout.Builder.obtain(
                record.apiResponse,
                0,
                record.apiResponse.length,
                textPaint,
                contentWidth.toInt()
            )
                .setAlignment(Layout.Alignment.ALIGN_NORMAL)
                .setLineSpacing(0f, 1.25f)
                .setIncludePad(false)
                .build()
        } else {
            @Suppress("DEPRECATION")
            StaticLayout(
                record.apiResponse,
                textPaint,
                contentWidth.toInt(),
                Layout.Alignment.ALIGN_NORMAL,
                1.25f,
                0f,
                false
            )
        }

        canvas.save()
        canvas.translate(margin, currentY)
        textLayout.draw(canvas)
        canvas.restore()

        // 5. Footer
        val footerY = pageHeight - margin
        paint.color = Color.rgb(226, 232, 240)
        paint.strokeWidth = 1f
        canvas.drawLine(margin, footerY - 14f, pageWidth - margin, footerY - 14f, paint)

        paint.color = Color.rgb(148, 163, 184)
        paint.textSize = 8f
        paint.typeface = Typeface.DEFAULT
        canvas.drawText(
            "FlyVision Drosophila Neurological Surface Inspection • Confidential Research",
            margin,
            footerY,
            paint
        )

        val pageLabel = "Page 1 of 1"
        val pageLabelWidth = paint.measureText(pageLabel)
        canvas.drawText(pageLabel, pageWidth - margin - pageLabelWidth, footerY, paint)

        document.finishPage(page)

        // Write to cache file
        val reportsDir = File(context.cacheDir, "reports").apply { mkdirs() }
        val outputFile = File(reportsDir, "inspection_summary_${record.id}_${System.currentTimeMillis()}.pdf")
        FileOutputStream(outputFile).use { fos ->
            document.writeTo(fos)
        }
        document.close()

        return outputFile
    }

    private fun loadSpecimenBitmap(context: Context, uriString: String?): Bitmap? {
        if (uriString.isNullOrBlank()) return null
        return try {
            val options = BitmapFactory.Options().apply {
                inSampleSize = 2 // Downsample for efficient PDF embedding
            }
            if (uriString.startsWith("content://")) {
                val uri = Uri.parse(uriString)
                context.contentResolver.openInputStream(uri)?.use { stream ->
                    BitmapFactory.decodeStream(stream, null, options)
                }
            } else {
                val file = File(uriString)
                if (file.exists()) {
                    BitmapFactory.decodeFile(file.absolutePath, options)
                } else null
            }
        } catch (e: Exception) {
            null
        }
    }

    private fun scaleBitmapToFit(src: Bitmap, maxWidth: Int, maxHeight: Int): Bitmap {
        val width = src.width
        val height = src.height
        val ratio = minOf(maxWidth.toFloat() / width, maxHeight.toFloat() / height)
        val targetWidth = (width * ratio).toInt().coerceAtLeast(1)
        val targetHeight = (height * ratio).toInt().coerceAtLeast(1)
        return Bitmap.createScaledBitmap(src, targetWidth, targetHeight, true)
    }
}
